# 
# Healthcheck dient zur Kontrolle... ob die DB wirklich bereit ist
# Express -> Mongo Web oberfläche Aufrufen
# Volume speichert dauerhaft (Directorie) auf der Festplatte, auch wenn container stoppt


# Anker bei dem Docker alles was mit x- beginnt ignoriert (Wichtig! sonst Error)
x-logging: &logging-config
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_db
    logging: *logging-config
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand({ping:1})'"]  #Ist DB bereit? -> ping
      interval: 10s
      timeout: 5s
      retries: 4
      # NEU: Watchtower Erlaubnis: Nur dieser Container wird automatisch geupdated !!
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    deploy:
      resources:
        limits:
          memory: 2GB
        reservations: 
          memory: 256MB

# build -> Docker sucht nach "Dockerfile"
# condition -> wartet bis healthcheck erfolgreich war
  app:
    build: .
    container_name: node_app
    command: npx nodemon server.js    #NEU: Startet Nodemon nur noch in der lokalen Entwicklung
    ports:
     - "3000:3000"
    volumes:
      - .:/usr/src/app                # Live-Sync (Dadurch 'sieht ' der Container  lokale Änderungen und reagiert darauf) 
      - /usr/src/app/node_modules     # Verhindert das Überschreiben durch lokale Module
    environment:
      - MONGO_URI=mongodb://mongodb:27017/kursverwaltung
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:                      #NEU: Healthcheck ob Express-Server auf Port 3000 erreichbar ist   (curl muss installiert sein)
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 3
      start_period: 30s       #Zeit zum Booten geben

    logging: *logging-config
    deploy:
      resources:
        limits:
          memory: 512MB
        reservations: 
          memory: 128MB

  watchtower:
    image: containrrr/watchtower   # schreibt man wirklich mit 3 r lol
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
        # Intervall in Sekunden Nicht Millisek. (3600s = 1 Stunde)
      - WATCHTOWER_POLL_INTERVAL=3600
        # Löscht alte Images nach dem Update
      - WATCHTOWER_CLEANUP=true
        # Wichtig: Nur Container mit dem speziellen Label updaten
      - WATCHTOWER_LABEL_ENABLE=true
    restart: unless-stopped    # automatischer Neustart (außer manuell)

    logging: *logging-config

    deploy:
      resources:
        limits:
          memory: 128MB
        reservations: 
          memory: 50MB
# volumes
volumes:
  mongodb_data:


# docker volume inspect mongodb_data              -> Mountpoint zeigt wo die Daten liegen und vereinfacht das Backup
# docker volume inspect dao_teil_4_mongodb_data   -> Zeigt wo docker die Daten auf Windows-System 'versteckt'    => Mountpoint": "/var/lib/docker/volumes/dao_teil_4_mongodb_data/_data",


# http://localhost:3000/html/start.html



